version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: homeops-sentinel_web_1
      APP_PORT: 4747

  web:
    image: ghcr.io/brainx/homeops-sentinel-umbrel:0.2.0@sha256:931c64accb43a39bf5a93eac2859a1bbcc8c5802a2cccde2fbbff794be6dded4
    restart: on-failure
    stop_grace_period: 20s
    environment:
      HOST: 0.0.0.0
      PORT: 4747
      HOMEOPS_DATA_DIR: /data
      HOMEOPS_STATIC_DIR: /app/dist
      APP_SEED: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
