version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: homeops-sentinel_web_1
      APP_PORT: 4747

  web:
    image: ghcr.io/brainx/homeops-sentinel-umbrel:0.1.0@sha256:78baddeadde8247b36c9691ae17e72abbd1e87cf58a083fa1922ca432c0bdb94
    restart: on-failure
    stop_grace_period: 20s
    environment:
      HOST: 0.0.0.0
      PORT: 4747
      HOMEOPS_DATA_DIR: /data
      HOMEOPS_STATIC_DIR: /app/dist
      APP_SEED: ${APP_SEED}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
